### ISSUE TITLE
Uncaught TypeError: dateToBz is not a function

### ISSUE THREAD

**Issue by karlt** [mozilla/media-triage#7]
`dateToBz()` calls have been [added](https://github.com/mozilla/media-triage/commit/c1efa9ebceefc8094393fee6ee6b53fcc0782c03#diff-1e20a0ee0fa5c5689cd8541a5892e5e23248b3bf2ab918043e525c443856f18cR239) to `parseICS()` function scope, but `dateToBz()` is [defined](https://github.com/mozilla/media-triage/blob/c1efa9ebceefc8094393fee6ee6b53fcc0782c03/js/utils.js#L155-L183) only within the `for` loop.

Moving the function resolves that error but leaves
"Uncaught TypeError: date is null".

`git checkout ad43646ce611a3eff26032b1816c0c4c29a24f8e` resolves both `TypeError`s.

**Comment by jmathies** [comment]
Odd, on Windows I do not get the error, but I can see how it occurs. I'm also poking at why those min and max dates seemed to be working correctly in my environment!
